In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
eeg_data = pd.read_csv('./EEG/eeg-data.csv', low_memory=False)
eeg_data.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
def extract_eeg_lists(eeg_power_str):
    return [float(n) for n in eeg_power_str.split("[")[1].split("]")[0].split(",")]
eeg_data.eeg_power = eeg_data.eeg_power.apply(extract_eeg_lists)
eeg_data.raw_values = eeg_data.raw_values.apply(extract_eeg_lists)
print(eeg_data.shape)

(30013, 13)

In [4]:
eeg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30013 entries, 0 to 30012
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              30013 non-null  int64
 1   id                 30013 non-null  int64
 2   indra_time         30013 non-null  object
 3   browser_latency    30013 non-null  object
 4   reading_time       30013 non-null  object
 5   attention_esense   30013 non-null  int64
 6   meditation_esense  30013 non-null  int64
 7   eeg_power          30013 non-null  object
 8   raw_values         30013 non-null  object
 9   signal_quality     30013 non-null  int64
 10  createdAt          30013 non-null  object
 11  updatedAt          30013 non-null  object
 12  label              30013 non-null  object
dtypes: int64(5), object(8)
memory usage: 3.0+ MB

In [7]:
eeg_data[['eeg_power','raw_values','label']].head(1)

,eeg_power,raw_values,label
0,"[944412.0, 111373.0, 52404.0, 28390.0, 3237.0,...","[-203.0, -202.0, -196.0, -185.0, -163.0, -137....",unlabeled

In [8]:
print(f"size of each eeg power: {len(eeg_data.eeg_power[0])}")
print(f"size of each raw value: {len(eeg_data.raw_values[0])}")

size of each eeg power: 8
size of each raw value: 512

In [9]:
eeg_data.label.value_counts().keys()

Index(['unlabeled', 'relax', 'music', 'video-ver2', 'thinkOfItems-ver2',
       'colorInstruction2', 'video-ver1', 'thinkOfItems-ver1',
       'thinkOfItemsInstruction-ver2', 'colorInstruction1',
       'thinkOfItemsInstruction-ver1', 'videoInstruction', 'mathInstruction',
       'relaxInstruction', 'musicInstruction', 'blinkInstruction',
       'colorRound1-3', 'colorRound1-4', 'colorRound1-1', 'colorRound1-2',
       'colorRound1-5', 'colorRound1-6', 'colorRound5-3', 'readyRound5',
       'readyRound4', 'colorRound2-4', 'readyRound2', 'readyRound1',
       'colorRound2-1', 'colorRound5-5', 'colorRound2-2', 'colorRound2-5',
       'colorRound5-2', 'colorRound5-6', 'readyRound3', 'colorRound2-6',
       'colorRound2-3', 'colorRound5-1', 'colorRound5-4', 'math10', 'math8',
       'math2', 'math6', 'math4', 'math11', 'math12', 'math7', 'math3',
       'math5', 'math9', 'math1', 'colorRound3-2', 'colorRound3-4',
       'colorRound3-3', 'colorRound3-5', 'colorRound3-1', 'blink5', 'blink1',
       'colorRound3-6', 'blink3', 'blink2', 'blink4', 'colorRound4-6',
       'colorRound4-3', 'colorRound4-5', 'colorRound4-2', 'colorRound4-1',
       'colorRound4-4'],
      dtype='object', name='label')

In [ ]:
import ast

min_eeg_power = ast.literal_eval(
    eeg_data.loc[eeg_data.signal_quality.eq(eeg_data.signal_quality.min()), "eeg_power"].iloc[0]
)[0]
max_eeg_power = ast.literal_eval(
    eeg_data.loc[eeg_data.signal_quality.eq(eeg_data.signal_quality.max()), "eeg_power"].iloc[0]
)[0]

print(float(min_eeg_power))
# plt.scatter(max_eeg_power, min_eeg_power)
# plt.xlabel("eeg_power at max signal_quality (first band)")
# plt.ylabel("eeg_power at min signal_quality (first band)")
# plt.scatter(eeg_data.eeg_power[eeg_data.signal_quality == eeg_data.signal_quality.max()].iloc[0],
            # eeg_data.eeg_power[eeg_data.signal_quality == eeg_data.signal_quality.min()].iloc[0])

# Stimulus

In [ ]:
stim_data = pd.read_csv('/Users/parhamkebria/Desktop/eeg/EEG/stimulus-times.csv', low_memory=False)
print(stim_data.shape)
stim_data.head(2)

# Subject Metadata

In [ ]:
subject_data = pd.read_csv("/Users/parhamkebria/Desktop/eeg/EEG/subject-metadata.csv", low_memory=False)
print(subject_data.shape)
subject_data.head(2)

# NatIPAN

In [7]:
activity = "Catch"
trial = 1
nat = pd.read_csv(f"/Users/parhamkebria/Documents/IPAN/IPANNat23Aug23/outputs/output_video_{activity}_trial_{trial}.csv", low_memory=False)
print(nat.shape)
nat.head(2)

(97, 8)

,l_shoulder,l_elbow,l_hip,l_knee,r_shoulder,r_elbow,r_hip,r_knee
0,81.087139,54.964325,171.991852,177.084473,101.775761,10.558552,173.452623,179.253894
1,80.919544,57.293616,171.888918,177.353783,101.920808,17.815247,173.500584,179.089756